import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/sidebar";
import style from "./page.module.css";
import AuthProvider from "@/context/auth";
import CallbackUrl from "@/context/login";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <CallbackUrl>
        <body className={inter.className}>
          <div
            style={{
              display: "flex",
              minHeight: "100vh",
            }}
          >
            <Sidebar />
            <AuthProvider>
              <main
                style={{
                  flexGrow: 1,
                  position: "relative",
                }}
                className={style.main}
              >
                {children}
              </main>
            </AuthProvider>
          </div>
        </body>
      </CallbackUrl>
    </html>
  );
}
